###############################################
# Evergreen Template for AI-ML-Testing Pipeline
###############################################

# Mark a failure as a system/bootstrap failure (purple box) rather then a task
# failure by default.
# Actual testing tasks are marked with `type: test`
command_type: system

# Protect yourself against rogue test case, or curl gone wild, that runs forever
# Good rule of thumb: the averageish length a task takes, times 5
# That roughly accounts for variable system performance for various buildvariants
exec_timeout_secs:
  3600 # 60 minutes is the longest we'll ever run (primarily
  # for macos hosts)

# What to do when evergreen hits the timeout (`post:` tasks are run automatically)
timeout:
  - command: shell.exec
    params:
      script: |
        ls -la

functions:
  "fetch source":
    - command: git.get_project
      type: setup
      params:
        directory: "src"

  "fetch secrets":
    - command: subprocess.exec
      type: setup
      params:
        working_dir: "src"
        binary: bash
        args: [.evergreen/fetch-secrets.sh]

  "fetch repo":
    - command: shell.exec
      type: setup
      params:
        working_dir: "src"
        script: |
          if [ ! -d "${DIR}" ]; then
            echo '${REPO_NAME} could not be found' 1>&2
            exit 1
          fi
          # Apply patches to upstream repo if desired.
          cd ${DIR}
          git clone ${CLONE_URL}
          if [ -d "patches" ]; then
            cd ${REPO_NAME}
            echo "Applying patches."
            git apply  ../patches/*
          fi

  "execute tests":
    - command: subprocess.exec
      type: test
      params:
        add_expansions_to_env: true
        working_dir: "src/${DIR}/${REPO_NAME}"
        binary: bash
        args:
          - ../run.sh

  "setup local atlas":
    - command: subprocess.exec
      type: setup
      retry_on_failure: true
      params:
        add_expansions_to_env: true
        working_dir: "src"
        binary: bash
        args:
          - .evergreen/provision-atlas.sh

pre_error_fails_task: true
pre:
  - func: "fetch source"
  - func: "fetch secrets"

tasks:
  - name: test-semantic-kernel-python-local
    commands:
      - func: "fetch repo"
      - func: "setup local atlas"
      - func: "execute tests"

  - name: test-semantic-kernel-python-remote
    commands:
      - func: "fetch repo"
      - func: "execute tests"

  - name: test-semantic-kernel-csharp-local
    commands:
      - func: "fetch repo"
      - func: "setup local atlas"
      - func: "execute tests"

  - name: test-semantic-kernel-csharp-remote
    commands:
      - func: "fetch repo"
      - func: "execute tests"

  - name: test-langchain-python-local
    commands:
      - func: "fetch repo"
      - func: "setup local atlas"
      - func: "execute tests"

  - name: test-langchain-python-remote
    commands:
      - func: "fetch repo"
      - func: "execute tests"

  - name: test-chatgpt-retrieval-plugin-local
    commands:
      - func: "fetch repo"
      - func: "setup local atlas"
      - func: "execute tests"

  - name: test-chatgpt-retrieval-plugin-remote
    commands:
      - func: "fetch repo"
      - func: "execute tests"

  - name: test-llama-index-local
    commands:
      - func: "fetch repo"
      - func: "setup local atlas"
      - func: "execute tests"

  - name: test-llama-index-remote
    commands:
      - func: "fetch repo"
      - func: "execute tests"

  # TODO: INTPYTHON-313
  # - name: test-docarray-local
  #   commands:
  #     - func: "fetch repo"
  #     - func: "setup local atlas"
  #     - func: "execute tests"

  - name: test-docarray-remote
    commands:
      - func: "fetch repo"
      - func: "execute tests"

buildvariants:
  - name: test-llama-index-kvstore-rhel
    # TODO - Maintainer has pushed back on this.
    display_name: LlamaIndex RHEL KV Store
    expansions:
      DIR: llama-index-python-kvstore
      REPO_NAME: llama_index
      # TODO - Update CLONE_URL: [PYTHON-4522] [INTPYTHON-326]
      CLONE_URL: -b PYTHON-4522 --single-branch https://github.com/shruti-sridhar/llama_index.git
      DATABASE: llama_index_test_db
    run_on:
      - rhel87-small
    tasks:
      - name: test-llama-index-local
      - name: test-llama-index-remote
        batchtime: 10080  # 1 week

  - name: test-semantic-kernel-python-rhel
    display_name: Semantic-Kernel RHEL Python
    expansions:
      DIR: semantic-kernel-python
      REPO_NAME: semantic-kernel
      CLONE_URL: https://github.com/microsoft/semantic-kernel.git
      DATABASE: pyMSKTest
    run_on:
      - rhel87-small
    tasks:
      - name: test-semantic-kernel-python-local
      - name: test-semantic-kernel-python-remote
        batchtime: 10080  # 1 week

  - name: test-semantic-kernel-csharp-rhel
    display_name: Semantic-Kernel RHEL CSharp
    expansions:
      DIR: semantic-kernel-csharp
      REPO_NAME: semantic-kernel
      CLONE_URL: https://github.com/microsoft/semantic-kernel.git
      DATABASE: dotnetMSKNearestTest
    run_on:
      - rhel87-small
    tasks:
      - name: test-semantic-kernel-csharp-local
      - name: test-semantic-kernel-csharp-remote
        batchtime: 10080  # 1 week

  - name: test-langchain-python-rhel
    display_name: Langchain RHEL Python
    expansions:
      DIR: langchain-python
      REPO_NAME: langchain-mongodb
      CLONE_URL: https://github.com/langchain-ai/langchain-mongodb.git
      DATABASE: langchain_test_db
    run_on:
      - rhel87-small
    tasks:
      - name: test-langchain-python-local
      - name: test-langchain-python-remote
        batchtime: 10080  # 1 week

  - name: test-chatgpt-retrieval-plugin-rhel
    display_name: ChatGPT Retrieval Plugin
    expansions:
      DIR: chatgpt-retrieval-plugin
      REPO_NAME: chatgpt-retrieval-plugin
      CLONE_URL: https://github.com/openai/chatgpt-retrieval-plugin.git
      DATABASE: chatgpt_retrieval_plugin_test_db
    run_on:
      - rhel87-small
    tasks:
      - name: test-chatgpt-retrieval-plugin-local
      - name: test-chatgpt-retrieval-plugin-remote
        batchtime: 10080  # 1 week

  - name: test-llama-index-vectorstore-rhel
    display_name: LlamaIndex RHEL Vector Store
    expansions:
      DIR: llama-index-python-vectorstore
      REPO_NAME: llama_index
      # TODO: Update INTPYTHON-414
      CLONE_URL: -b INTPYTHON-414 --single-branch https://github.com/blink1073/llama_index.git
      DATABASE: llama_index_test_db
    run_on:
      - rhel87-small
    tasks:
      - name: test-llama-index-local
      - name: test-llama-index-remote
        batchtime: 10080  # 1 week

  - name: test-docarray-rhel
    display_name: DocArray RHEL
    expansions:
      DIR: docarray
      REPO_NAME: docarray
      CLONE_URL: https://github.com/docarray/docarray.git
      DATABASE: docarray_test_db
    run_on:
      - rhel87-small
    tasks:
      # TODO: INTPYTHON-313
      # - name: test-docarray-local
      - name: test-docarray-remote
        # batchtime: 10080  # 1 week
